// Generated by BUCKLESCRIPT VERSION 1.4.3, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives");

Pervasives.print_string("!!!!!!\n");

var msg = "Hello Reason!";

Pervasives.print_string(msg);

Pervasives.print_newline(/* () */0);

Pervasives.print_string("!!!!!!\n");

exports.msg = msg;
/*  Not a pure module */
